name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Install Docker for Mac
        run: brew install --cask docker
      - name: Launch Docker for Mac
        run: |
          open /Applications/Docker.app
          # Wait until Docker is ready
          while ! docker system info > /dev/null 2>&1; do sleep 1; done
        timeout-minutes: 5

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "ValveSoftware/Proton"
          ref: "proton_9.0"
          depth: 1
          submodules: recursive
          path: proton
      
      - name: configure
        run: mkdir build && cd build && ../proton/configure.sh

      - run: make wineopenxr
        working-directory: build